### ISSUE TITLE
Kick after %amount% seconds

### ISSUE THREAD

**Issue by davewanders** [NoneTirex/bpa#1]
If the player is online, and he wont login or register within a random customizable amount of seconds he will be kicked.

**Comment by RealTirex** [comment]
You can see [this update](https://www.spigotmc.org/resources/bungee-1-7-x-1-10-premium-authenticator-login-only-for-non-premium-extra-price.2750/update?update=173198). I added this feature.

**Comment by Artuto** [comment]
@NoneTirex How I can make that? i cant find the option in the config
