### ISSUE TITLE
Premium player register bug

### ISSUE THREAD

**Issue by davewanders** [NoneTirex/bpa#2]
When you set in your config that premium players can register, and they register, the next time they login they dont need to login?

Part of config: https://pastebin.com/sgdB6yHS

**Comment by RealTirex** [comment]
You can see [this update](https://www.spigotmc.org/resources/bungee-1-7-x-1-10-premium-authenticator-login-only-for-non-premium-extra-price.2750/update?update=173198). I fixed this bug.
